HotelRecruitment/Models/JobSeeker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class JobSeeker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Typeofposition { get; set; }
        public string workplace { get; set; }
        public string Position { get; set; }
        public string CV { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> IsInterview { get; set; }
        
     
        HttpPostedFileBase File { get; set; }

    }
}

HotelRecruitment/Controllers/JobSeekerController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelRecruitment.Controllers
{
    public class JobSeekerController : Controller
    {
        HotelManagementEntities dbContext = new HotelManagementEntities();
        //
        // GET: /JobSeeker/
        public ActionResult RegistrationOld()
        {
            return View();
        }
        public ActionResult Registration()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Registration(JobSeeker model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    DAL.JobSeeker jobSeeker = new DAL.JobSeeker();

                    jobSeeker.Name = model.Name;

                    jobSeeker.Email = model.Email;
                    jobSeeker.Mobile = model.Mobile;
                    jobSeeker.Salary = model.Salary;
                    jobSeeker.Typeofposition = model.Typeofposition;
                    jobSeeker.Position = model.Position;
                    jobSeeker.workplace = model.workplace;
                    jobSeeker.IsActive = false;
                    jobSeeker.IsDeleted = false;
                    jobSeeker.CreatedOn = DateTime.Now;


                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);

                        string fileExtension = Path.GetExtension(fileName);

                        if (fileExtension != ".pdf")
                        {
                            return View();
                        }
                        fileName = DateTime.Now.Ticks + fileName;

                        var path = Path.Combine(Server.MapPath("~/Content/Upload/CV/"), fileName);
                        file.SaveAs(path);
                        jobSeeker.CV = fileName.ToString();
                    }

                    dbContext.JobSeekers.Add(jobSeeker);
                    dbContext.SaveChanges();

                }

                catch (DbEntityValidationException e)
                {

                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw e;

                }

            }

            return RedirectToAction("Thankyou");
        }

        public ActionResult Update(int Id)
        {

            DAL.JobSeeker jobSeeker = dbContext.JobSeekers.Where(x => x.Id == Id).FirstOrDefault();
            Model.JobSeeker model = new Model.JobSeeker();
            model.Id = jobSeeker.Id;
            model.Name = jobSeeker.Name;
            model.Mobile = jobSeeker.Mobile;
            model.Email = jobSeeker.Email;
            model.Salary = jobSeeker.Salary;
            model.Typeofposition = jobSeeker.Typeofposition;
            model.workplace = jobSeeker.workplace;
            model.Position = jobSeeker.Position;
            model.CreatedOn = jobSeeker.CreatedOn;
            model.CV = jobSeeker.CV;
            model.IsActive = jobSeeker.IsActive;
            model.IsDeleted = jobSeeker.IsDeleted;

            return View(model);
        }
        [HttpPost]
        public ActionResult Update(JobSeeker model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    //DAL.JobSeeker jobSeeker = new DAL.JobSeeker();
                    //jobSeeker.Name = model.Name;
                    //jobSeeker.Email = model.Email;
                    //jobSeeker.Mobile = model.Mobile;
                    //jobSeeker.Salary = model.Salary;
                    //jobSeeker.Typeofposition = model.Typeofposition;
                    //jobSeeker.Position = model.Position;
                    //jobSeeker.workplace = model.workplace;
                    //jobSeeker.IsActive = true;
                    //jobSeeker.IsDeleted = false;
                    //jobSeeker.CreatedOn = DateTime.Now;

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);

                        string fileExtension = Path.GetExtension(fileName);

                        if (fileExtension != ".pdf")
                        {
                            return View();
                        }
                        fileName = DateTime.Now.Ticks + fileName;

                        var path = Path.Combine(Server.MapPath("~/Content/Upload/CV/"), fileName);
                        file.SaveAs(path);
                        model.CV = fileName.ToString();
                    }


                    dbContext.Entry(model).State = EntityState.Modified;
                    dbContext.SaveChanges();

                }

                catch (Exception ex)
                {

                    throw ex;

                    //foreach (var eve in e.EntityValidationErrors)
                    //{
                    //    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                    //        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    //    foreach (var ve in eve.ValidationErrors)
                    //    {
                    //        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                    //            ve.PropertyName, ve.ErrorMessage);
                    //    }
                    //}
                    //throw e;

                }

            } return RedirectToAction("Thankyou");
        }

        public ActionResult List()
        {
            return View();
            //return View(dbContext.JobSeekers.Where(x => x.IsDeleted == false).ToList().OrderByDescending(x => x.CreatedOn));
        }
        public ActionResult Thankyou()
        {
            return View();
        }
        public bool UpdateRating(int Rating, string Feedback, int JobSeekerId, bool IsInterview, bool IsActive)
        {

            var jobSeeker = dbContext.JobSeekers.Where(x => x.Id == JobSeekerId).FirstOrDefault();

            jobSeeker.Rating = Convert.ToInt32(Rating);
            jobSeeker.Feedback = Feedback;
            jobSeeker.IsInterview = IsInterview;
            jobSeeker.IsActive = IsActive;

            dbContext.SaveChanges();

            return true;
        }

        public ActionResult Index()
        {
            return View();
        }

    }
}

HotelRecruitment/Views/JobSeeker/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>landing page for job seeker</h2>

HotelRecruitment/Views/JobSeeker/List.cshtml
@model IEnumerable<DAL.JobSeeker>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="/Scripts/angular.min.js"></script>
<script src="/Scripts/JobSeeker/Module.js"></script>
<script src="/Scripts/JobSeeker/Service.js"></script>
<script src="/Scripts/JobSeeker/Controller.js"></script>
<div ng-controller="myCntrl">
    <div class="heading_part">
        <div class="center_container"><h2>Dashboard</h2></div><!---center_container--->
    </div><!---heading_part--->

    <div class="header_fullparts">
        <div class="center_container">
            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>{{employees.length}}</h2>
                <p>Number of CVS</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>5 <!--span><img src="images/email.png"/></span--></h2>
                <p>Number of Jobs</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>2 <!--span><img src="images/positon.png"/></span--></h2>
                <p>Sales</p>
            </div>

            <div class="col-xs-6 col-sm-3 parts_fullparts dashboard_parts">
                <h2>3 <!--span><img src="images/LAST.png"/></span--></h2>
                <p>Outstanding</p>
            </div>
        </div><!---center_container--->
    </div> <!---header_fullparts--->

    <div class="main_box_pernolinfo">
        <div class="col-xs-12 col-sm-12 cv_box">
            <h1 class="c_v">CV</h1>
            <div style=" height: 183px; border: 1px solid red; overflow: scroll; overflow-x: hidden; ">
                <table class="table-responsive cv_table">
                   
                    <tr style="background: #CCCCCC;">
                        <th class="dropdown">
                            <a href="#" ng-click="sortType = 'Name'; sortReverse = !sortReverse">
                                Name
                                <span ng-show="sortType == 'Name' && !sortReverse" class="fa fa-caret-down"></span>
                                <span ng-show="sortType == 'Name' && sortReverse" class="fa fa-caret-up"></span>
                            </a>
                        </th>
                        <th class="dropdown">
                            <a href="#" ng-click="sortType = 'Typeofposition'; sortReverse = !sortReverse">
                                Type
                                <span ng-show="sortType == 'Typeofposition' && !sortReverse" class="fa fa-caret-down"></span>
                                <span ng-show="sortType == 'Typeofposition' && sortReverse" class="fa fa-caret-up"></span>
                            </a>
                        </th>
                        <th class="dropdown">
                           
                            <a href="#" ng-click="sortType = 'Salary'; sortReverse = !sortReverse">
                                Salary
                                <span ng-show="sortType == 'Salary' && !sortReverse" class="fa fa-caret-down"></span>
                                <span ng-show="sortType == 'Salary' && sortReverse" class="fa fa-caret-up"></span>
                            </a>
                        </th>
                        <th class="dropdown">CV</th>
                        <th class="dropdown">Mobile</th>
                        <th class="dropdown">
                            <a href="#" ng-click="sortType = 'Email'; sortReverse = !sortReverse">
                                Email
                                <span ng-show="sortType == 'Email' && !sortReverse" class="fa fa-caret-down"></span>
                                <span ng-show="sortType == 'Email' && sortReverse" class="fa fa-caret-up"></span>
                            </a>
                        </th>
                        <th class="dropdown">Interveiw</th>
                        <th class="dropdown">
                            <a href="#" ng-click="sortType = 'Rating'; sortReverse = !sortReverse">
                                Rating
                                <span ng-show="sortType == 'Rating' && !sortReverse" class="fa fa-caret-down"></span>
                                <span ng-show="sortType == 'Rating' && sortReverse" class="fa fa-caret-up"></span>
                            </a>
                        </th>
                    </tr>
                    <tr ng-repeat="employee in employees | orderBy:sortType:sortReverse">
                        <td style="cursor:pointer;" ng-click="editEmployee(employee)">{{employee.Name}}</td>
                        <td>{{employee.Typeofposition}}</td>
                        <td>{{employee.Salary}}</td>
                        <td><a target="_blank" href="~/Content/Upload/Cv/{{employee.CV}}"><img style="width:18px;" src="../content/images/pdf.png" /></a></td>
                        <td>{{employee.Mobile}}</td>
                        <td>{{employee.Email}}</td>
                        <td><input onclick="return false" ng-checked="employee.IsInterview" ng-model="employee.IsInterview" name="chkJobSeeker" id="{{employee.Id}}" type="checkbox" /></td>
                        <td>{{employee.Rating}}</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 testimonial_part drill_down" ng-show="canShow">

            <div class="col-xs-12 col-sm-6 text_drilldown">
                <b style="font-size:28px;">{{Name}}</b>
                <p> <b>Type of position</b>{{Typeofposition}}</p>

                <p><b>Work area</b>{{workplace}}</p>


                @*<input type="checkbox" ng-model=IsActive ng-checked="{{IsActive}}" name="IsActive" /> Is Active ?<br />*@



            </div>
            <div class="col-xs-12 col-sm-6 text_drilldown">
                <p><b>Note</b></p>
                <p><textarea ng-model="Feedback" placeholder="Multitext"></textarea></p>
                <p class="text-left">
                    <select data-ng-options="o.name for o in options" data-ng-model="selectedOption"></select>
                    <input type="checkbox" ng-model=IsInterview ng-checked="{{IsInterview}}" name="IsInterview" /> Is Interview ?
                    <input type="submit" value="Submit" style="margin-left:50px;" class="btn btn-default" ng-click="UpdateEmployee()" />
                </p>



            </div>
        </div>
    </div>  <!---main_box_pernolinfo--->
</div>

HotelRecruitment/Views/JobSeeker/List1.cshtml
@model IEnumerable<Model.JobSeeker>

@{
    ViewBag.Title = "List1";
}

<h2>List1</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MobileVerificationCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Typeofposition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.workplace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CV)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mobile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MobileVerificationCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Typeofposition)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.workplace)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CV)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

HotelRecruitment/Views/JobSeeker/Registrationold.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<script src="/Scripts/angular.min.js"></script>
<script src="/Scripts/JobSeeker/Module.js"></script>
<script src="/Scripts/JobSeeker/Service.js"></script>
<script src="/Scripts/JobSeeker/Controller.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $('form').submit(function () {
            if ($(this).valid()) {
                setTimeout(Redirect, 1000);
            }
        });
    });

    function Redirect() {
        window.location = 'http://localhost:23758/jobseeker/Thankyou';
    }
</script>

<div ng-controller="myCntrl">

    <form name="registerform" action="/api/jobseekerregistrationservice" enctype="multipart/form-data" ng-submit="submit()" method="post">
        <div class="heading_part">
            <div class="center_container"><h2>Submit Your CV</h2></div>
        </div>
        <div class="header_fullparts">
            <div class="center_container">
                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Name</h2>
                    <input type="text" ng-model="Name" name="Name" placeholder="Enter your name" required />
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>E-mail</h2>
                    <input type="email" ng-model="Email" name="Email" placeholder="Email Address" ng-required="true" />

                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Position</h2>
                    <input type="text" ng-model="Position" name="Position" placeholder="Current position" />
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>CV</h2>
                    <input type="file" name="File" accept=".pdf" style="margin-left: -2px; border: 0;" />
                </div>
            </div>
        </div>

        <div class="persnol_imformation">
            <div class="center_container">
                <h1>Personal Imformation</h1>
            </div>
        </div>

        <div class="main_box_pernolinfo">
            <div class="col-xs-12 col-sm-6 text_boxes">
                <p>
                    <input type="text" ng-model="Mobile" name="Mobile" placeholder="Mobile phone number" ng-required="true" />
                </p>
                <p>
                    <input type="text" ng-model="Salary" name="Salary" placeholder="Current salary" />
                </p>
                <p>
                    <textarea rows="3" ng-model="Typeofposition" name="Typeofposition" placeholder="What type of Position Are you looking For?"></textarea>
                </p>
                <p>
                    <textarea rows="3" ng-model="workplace" name="workplace" placeholder="Where you you want to work? in Sri Lanka or somewhere else in the world?"></textarea>
                </p>
                <div class="form-group">
                    <div>
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 testimonial_part">
                <div class="col-xs-6 col-sm-7 text_testimonial">
                    <p>Hi</p>
                    <p>
                        Upload your CV to my website and I will do my best to find a new position for you. I can not promise anything, but I will give you feedback during the process. I suggest to check your email or keep your mobile with you.
                    </p>
                    <p class="text-right"><img src="~/content/images/IMG_24052016_114029.png" /></p>
                </div>
                <div class="col-xs-6 col-sm-5 img_testimonial">
                    <img class="img-circle" src="~/content/images/lady.png" />
                </div>
            </div>
        </div>

    </form>
</div>

HotelRecruitment/Views/JobSeeker/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

HotelRecruitment/Views/JobSeeker/Thankyou.cshtml
@{
    ViewBag.Title = "Thankyou";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h1>
    Thankyou for submitting your information
</h1>

HotelRecruitment/Views/JobSeeker/Update.cshtml
@model Model.JobSeeker

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="heading_part">
    <div class="center_container"><h2>Update Your CV</h2></div><!---center_container--->
</div>

    @using (Html.BeginForm("Update", "JobSeeker", FormMethod.Post, new { @class = "form-vertical", role = "form1", @autocomplete = "off", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedOn)
        @Html.HiddenFor(model => model.CV)
        @Html.HiddenFor(model => model.IsActive)
        @Html.HiddenFor(model => model.IsDeleted)

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="header_fullparts">
            <div class="center_container">
                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Name</h2>
                    @Html.TextBoxFor(model => model.Name, new { @placeholder = "Enter your name" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Email</h2>
                    @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email Address" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>Position</h2>
                    @Html.TextBoxFor(model => model.Position, new { @placeholder = "Current position" })
                </div>

                <div class="col-xs-6 col-sm-3 parts_fullparts">
                    <h2>CV</h2>
                    <input type="file" name="file" class="file" style="margin-left:-2px;border:none;">
                </div>
            </div>
        </div>

        <div class="persnol_imformation">
            <div class="center_container">
                <h1>Persnol Imformation</h1>
            </div>
        </div> 

        <div class="main_box_pernolinfo">
            <div class="col-xs-12 col-sm-6 text_boxes">

                <p>@Html.TextBoxFor(model => model.Mobile, new { @placeholder = "Mobile phone number" })</p>
                <p>@Html.TextBoxFor(model => model.Salary, new { @placeholder = "Current salary" })</p>
                <p>@Html.TextAreaFor(model => model.Typeofposition, new { @placeholder = "What type of Position Are you looking For?" })</p>
                <p>@Html.TextAreaFor(model => model.workplace, new { @placeholder = "Where you you want to work? in Sri Lanka or somewhere else in the world?" })</p>
                <div class="form-group">
                    <div>
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 testimonial_part">
                <div class="col-xs-6 col-sm-7 text_testimonial">
                    <p>Hi</p>
                    <p>
                        Upload your CV to my website and I will do my best to find a new position for you. I can not promise anything, but I will give you feedback during the process. I suggest to check your email or keep your mobile with you.
                    </p>
                    <p class="text-right"><img src="~/content/images/IMG_24052016_114029.png" /></p>
                </div>
                <div class="col-xs-6 col-sm-5 img_testimonial">
                    <img class="img-circle" src="~/content/images/lady.png" />
                </div>
            </div>
        </div>
        
        
    }